version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=payment
      - MYSQL_USER=payment
      - MYSQL_PASSWORD=payment
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
