version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=checkout
      - MYSQL_USER=checkout
      - MYSQL_PASSWORD=checkout
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
