version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
#      - 3306:3306
#      unit test
      - 3303:3306
    environment:
      - MYSQL_DATABASE=product
      - MYSQL_USER=product
      - MYSQL_PASSWORD=product
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
#  redis:
#    image: 'redis:latest'
#    ports:
#      - 6379:6379
