version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=order
      - MYSQL_USER=order
      - MYSQL_PASSWORD=order
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
